firewall-cmd --add-port 80/tcp --permanent
firewall-cmd --add-port 2379-2380/tcp --permanent
firewall-cmd --add-port 8472/udp --permanent
firewall-cmd --add-port 4240/tcp --permanent
firewall-cmd --add-port 4244/tcp --permanent
firewall-cmd --add-port 4245/tcp --permanent
firewall-cmd --add-port 6942/tcp --permanent
firewall-cmd --add-port 9090/tcp --permanent
firewall-cmd --add-port 9876/tcp --permanent
firewall-cmd --add-port 9890/tcp --permanent
firewall-cmd --add-port 9891/tcp --permanent
firewall-cmd --add-port 9892/tcp --permanent
firewall-cmd --add-port 9893/tcp --permanent