apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: monitoring
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert
  issuerRef:
    name: test-selfsigned