---
elasticsearchHosts: "http://elasticsearch-master.logging:9200"
replicas: 1

image: "docker.elastic.co/kibana/kibana"
imageTag: "7.10.2"

resources:
  requests:
    cpu: "512m"
    memory: "1500Mi"
  limits:
    cpu: "512m"
    memory: "1500Mi"

tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

ingress:
  enabled: true
  annotations:
    # ingress.kubernetes.io/ssl-redirect: "true"
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: "nginx"
  path: /
  hosts:
    - kibana.yohanna.id
  # tls:
  #   - secretName: letsencrypt-staging
  #     hosts:
  #     - kibana.yohanna.id