---
elasticsearchHosts: "http://elasticsearch-master.logging.svc:9200"
replicas: 1

image: "docker.elastic.co/kibana/kibana"
imageTag: "7.10.2"

resources:
  requests:
    cpu: "512m"
    memory: "1500Mi"
  limits:
    cpu: "512m"
    memory: "1500Mi"

tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  path: /
  hosts:
    - kibana.yohanna.local.com